server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - RewritePath=/api/orders(?<segment>/?.*), /products$\{segment}
            - name: AuthenticationFilter

        - id: order-service-route
          uri: lb://distrubutor-service
          predicates:
            - Path=/api/distrubutors/**
          filters:
            - RewritePath=/api/distrubutors(?<segment>/?.*), /orders$\{segment}
            - name: AuthenticationFilter

        - id: user-service-route
          uri: lb://staff-service
          predicates:
            - Path=/api/staffs/**
          filters:
            - RewritePath=/api/staffs(?<segment>/?.*), /users$\{segment}
            - name: AuthenticationFilter
jwt:
  secret: bXktc3VwZXItc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktZm9yLWp3dC1zaWduYXR1cmUtZGRkY2YtMzZiNC00MWQ5LWE0ZmU=
