server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': 
            allowed-origins: "http://localhost:3000" 
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers: "*" 
            max-age: 3600 
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service-route
          uri: lb://order-service        
          predicates:
            - Path=/api/orders/**      
          filters:
            - RewritePath=/api/orders(?<segment>/?.*), /api/orders$\{segment}

        - id: distributor-service-route
          uri: lb://distributor-service 
          predicates:
            - Path=/api/distributors/** 
          filters:
            - RewritePath=/api/distributors(?<segment>/?.*), /api/distributors$\{segment}

        - id: staff-service-route
          uri: lb://staff-service 
          predicates:
            - Path=/api/staffs/**  
          filters:
            - RewritePath=/api/staffs(?<segment>/?.*), /api/staffs$\{segment}

jwt:
  secret: bXktc3VwZXItc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktZm9yLWp3dC1zaWduYXR1cmUtZGRkY2YtMzZiNC00MWQ5LWE0ZmU=
