server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distributor_db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    enabled: true
  group-configs:
    - group: 'distrubutor-service'
      paths-to-match: '/api/distributors/**'
