server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distributor_db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  group-configs:
    - group: 'distributor-service'
      paths-to-match: '/api/distributor/**'
