server:
  port: 8081

spring:
  application:
    name: staff-service
  datasource:
    url: jdbc:postgresql://localhost:5432/staff_db
    username: postgres
    password: 12345
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
